### ISSUE TITLE
CPU满载

### ISSUE THREAD

**Issue by wa4675518** [nofeeeth/NoDevFee#1]
经常跑着跑着CPU就满载了，不知道是什么原因
![1](https://user-images.githubusercontent.com/22948146/104085007-30ef8c00-5287-11eb-8d3d-0c003893a0a2.jpg)

**Comment by nofeeeth** [comment]
V1.3版本已解决

wa4675518 <notifications@github.com> 于2021年1月9日周六 下午2:30写道：
