### ISSUE TITLE
Can't intercept nbminer

### ISSUE THREAD

**Issue by EasyDing** [nofeeeth/NoDevFee#2]

**Comment by nofeeeth** [comment]
I only tested for Phoneix，maybe support for next version

HHHHappy.D <notifications@github.com> 于2021年2月11日周四 下午5:30写道：

**Comment by EasyDing** [comment]
Thanks for your reply, I will look forward to the new version

**Comment by nofeeeth** [comment]
V2.0 update content:
1. Fix the problem of high CPU usage
2. Increase en_us language selection
3. Increase NBMiner&T-rex core interception
