### ISSUE TITLE
Working with TRex and about languages

### ISSUE THREAD

**Issue by Tyson44-rus** [nofeeeth/NoDevFee#3]
As I understand it, your program does not yet know how to work with TRex? And I wanted to ask to make a choice of language in the program. Do at least some more English, please.
![image](https://user-images.githubusercontent.com/55685708/108414363-32748280-723d-11eb-9e65-4be56f8da526.png)

**Comment by nofeeeth** [comment]
Looking forward to the new version

Tyson44-rus <notifications@github.com> 于2021年2月19日周五 上午4:01写道：

**Comment by nofeeeth** [comment]
V2.0 update content:
1. Fix the problem of high CPU usage
2. Increase en_us language selection
3. Increase NBMiner&T-rex core interception

**Comment by Tyson44-rus** [comment]
Hello. I tried to run it with the new version of T-Rex and there is no interception ... I changed the name of the program, RandomTitle on.
![image](https://user-images.githubusercontent.com/55685708/108786818-83f67780-7585-11eb-9431-6fd9a15765cd.png)

**Comment by nofeeeth** [comment]
You should observe for hours

Tyson44-rus <notifications@github.com> 于2021年2月23日周二 上午8:16写道：

**Comment by Tyson44-rus** [comment]
Worked all day and there are no reports of interception. Are you sure your program works with this miner? I did everything according to the instructions, everything works with another miner (Phoenix).
![image](https://user-images.githubusercontent.com/55685708/108978097-4d5e5100-769a-11eb-9f76-35275b89e2fd.png)
